### ISSUE TITLE
Feed not exporting all "enabled" markdown pages

### ISSUE THREAD

**Issue by staghouse** [webmasterish/vuepress-plugin-feed#5]
## Description

I have added the following to all my markdown pages in frontmatter in Vuepress

```
{
  ...
  "feed": {
    "enable": "true"
  }
}
```

yet not _all_ pages get added to my exported file.

## Expected Behavior

All routes should be included in the outputted file. For me that is `atom.xml`

## Actual Behavior

Not all routes get included for not clear reason. Virtually all pages have the same type of frontmatter data with the `enable` flag set to true at the bottom of the JSON (my preferred structure of frontmatter)

## Steps to Reproduce

1. add the above frontmatter json
2. vuepress build docs
3. view outed files in dist

## Your Environment

| Description           | Value                                           |
|-----------------------|-------------------------------------------------|
| vuepress-plugin-feed version | 0.1.6    |
| node version          | ^11.9.0             |
| npm version           | yarn ^1.6.0              |
| browser               | not relevant  |
| OS                    | macOs 10.14.4               |

**Comment by webmasterish** [comment]
Hi @staghouse 

There are 2 functionalities that control the pages that get added to a feed:
1. The [`is_feed_page()`](https://github.com/webmasterish/vuepress-plugin-feed/blob/ee48eee313a3cf6dc109c24077c0fc051e17376c/index.js#L396-L455) function, which you can [optionally override](https://github.com/webmasterish/vuepress-plugin-feed/blob/ee48eee313a3cf6dc109c24077c0fc051e17376c/index.js#L221-L223) in plugin options.
2. The max count of feed items ([defaults to 20](https://github.com/webmasterish/vuepress-plugin-feed/blob/ee48eee313a3cf6dc109c24077c0fc051e17376c/index.js#L227)),) also controlled through plugin options.

If that doesn't solve it, then I would be needing more details such as sharing your VuePress project.

**Comment by staghouse** [comment]
Thank you, the "count" key is what I had been missing. I adjusted that to overcompensate for the pages that I actually needed which was just over 20.
